### ISSUE TITLE
Error on EDIScanner xample

### ISSUE THREAD

**Issue by luiggicc** [BerryWorksSoftware/edireader#3]
I'm new on reading EDI Files, currently i need to understand really fast for my job. I was testing the EDIScanner project but it sends me an error.

Usage: EDIScanner inputfile [-o outputfile]
Exception in thread "main" java.lang.RuntimeException: Missing or invalid command line arguments
	at com.berryworks.edireader.demo.EDIScanner.badArgs(EDIScanner.java:149)
	at com.berryworks.edireader.demo.EDIScanner.main(EDIScanner.java:139)
C:\Users\Bottago SA\AppData\Local\NetBeans\Cache\8.2\executor-snippets\run.xml:53: Java returned: 1

Any suggestion what am i doing wrong?

**Comment by msimon3** [comment]
How are you passing in the command line arguments? It expects at minimum a file to parse...
